In [1]:
import numpy as np # numpy是用来做矩阵运算的

In [7]:
# genfromtxt 函数是np自带的打开文件的函数，delimiter是分隔符，dtype是数据格式
opentxt1 = np.genfromtxt("HomeWork.txt",encoding="utf-8",delimiter=",",dtype=str)
# print(type(opentxt1))
# print(opentxt1)
#print(help(np.genfromtxt)) #通过help(函数名)可以查看每一个函数下的具体功能
print(opentxt1)

[['时间长度' 'UV_Total(M)' 'PV_Total(M)' 'UV_🔺(M)' 'PV_🔺(M)' 'UV_by_month(M)'
  'PV_by_month(M)' '']
 ['前1个月' '51' '229' '51' '229' '51' '229' '']
 ['前2个月' '84' '434' '33' '205' '40' '204' '']
 ['前3个月' '116' '656' '32' '222' '41' '221' '']
 ['前4个月' '147' '869' '31' '213' '41' '212' '']
 ['前5个月' '179' '1090' '32' '221' '42' '218' '']
 ['前6个月' '205' '1283' '26' '193' '37' '195' '']
 ['前7个月' '233' '1484' '28' '200' '39' '201' '']
 ['前8个月' '259' '1650' '25' '167' '35' '167' '']
 ['前9个月' '285' '1831' '27' '181' '37' '185' '']
 ['前10个月' '313' '2026' '28' '195' '38' '190' '']
 ['前11个月' '340' '2183' '27' '157' '36' '165' '']
 ['前12个月' '369' '2345' '29' '163' '38' '165' '']
 ['前13个月' '390' '2490' '21' '144' '30' '141' '']]


In [16]:
arr_1 = np.array([1,2,3,4]) #一维
print(arr_1) 
arr_2 = np.array([1,2,3,4,[5,6,7,8]]) #二维
print(arr_2) 
arr_3 = np.array([1,2,3,4,[5,6,7,8,[9,10,11]]]) #三维
print(arr_3)

#切片和步长
arr_4 = arr_1[1:3:2] #2代表步长，一维数组与列表类似
print(arr_4)

arr_5 = np.array([np.arange(5),np.arange(5),np.arange(5)])
print(arr_5[0:2,1:3]) #二维数组切片有两个，分别是行切片和列切片

[1 2 3 4]
[1 2 3 4 list([5, 6, 7, 8])]
[1 2 3 4 list([5, 6, 7, 8, [9, 10, 11]])]
[2]
[[1 2]
 [1 2]]


In [7]:
"""
1.numpy.random.rand() 
官方文档中给出的用法是：numpy.random.rand(d0,d1,…dn) 
以给定的形状创建一个数组，并在数组中加入在[0,1]之间均匀分布的随机样本。
"""
data1 = np.random.rand(2,3) # 随机生成一个2行2列的矩阵,范围默认0到1，类型是浮点型
print(data1)
print('维度个数',data1.ndim)
print('各维度大小',data1.shape)
print('数据类型',data1.dtype)
print('元素个数',data1.size)

"""
3.numpy.random.randint() 
官方文档中给出的用法是：numpy.random.randint(low,high=None,size=None,dtype) 
生成在半开半闭区间[low,high)上离散均匀分布的整数值;若high=None，则取值区间变为[0,low) 
用法及实现 
high=None的情形 
"""
data2 = np.random.randint(0,10,size=(2,3)) # 随机生成一个2行2列的矩阵,范围可以指定，比如0到10,类型是整数
print(data2)


"""
2.numpy.random.randn() 
官方文档中给出的用法是：numpy.random.rand(d0,d1,…dn) 
以给定的形状创建一个数组，数组元素来符合标准正态分布N(0,1) 
若要获得一般正态分布则可用sigma * np.random.randn(…) + mu进行表示 
"""
data3 = 10 * np.random.randn(2,4)
print(data3)


"""
4.numpy.random.uniform(0,100,100)  
从零到100随机生成100个浮点类型的随机数
"""

data4 = np.random.uniform(0,100,100)
print(data4)

"""
5.正态分布
"""

data5 = np.random.normal(0,1,(10,10)) #均值为0，标准差为1，十行十列的正态分布
print(data5)

[[0.88882234 0.86244327 0.50788768]
 [0.63345682 0.6379651  0.60083536]]
维度个数 2
各维度大小 (2, 3)
数据类型 float64
元素个数 6
[[0 9 4]
 [3 3 5]]
[[-10.78474832 -13.72895478  10.97224973 -12.186602  ]
 [  0.18294363  -1.24719795  21.07385981  -8.42795136]]
[29.31569225 23.91638951 48.67265    96.45183745 19.19609962 59.49432895
 14.42229285 37.52635041 83.110468   50.8191762  97.99281724 35.94787284
  1.1223901  11.48925171 23.81040598  4.99110744  3.32087144 84.37909743
 33.68521322 33.07612949 41.77494947 88.95417609 13.63197654 34.27362571
 11.9816422  81.67879528 78.14058493 55.58483064 42.64116477 80.28271727
 31.82759861 95.04436115 61.20121452 26.46026057 37.58783969 59.78839512
 93.92069327 95.08910146 96.82744083 72.09069393 57.00228606 91.58104547
 45.63382232  6.63349487 68.96797441 72.79258402 94.32195529 44.99816173
 35.55480307 92.62929251 64.65659593 10.34426429  7.14468664 39.16516732
 46.0738393  12.93005159 49.40948388 11.37010282 86.64207385 98.70137901
 70.19864396 37.43936245 66

In [18]:
# 正态分布的逻辑运算
temp = data5[:5,:5].copy() #在data5基础上取5行5列，然后copy
temp

array([[ 0.98598865, -1.88432601,  0.13684278,  0.9404147 , -0.11515529],
       [-1.69726014,  0.52263901, -0.55892912, -0.91538695,  0.25244236],
       [-0.17848229,  1.91058176,  1.46580046,  0.31832621, -0.3068495 ],
       [ 0.79217788,  0.73246225, -0.34740352,  0.56494832,  2.29008694],
       [ 0.60976535, -1.51983301,  1.13985954,  1.47394263, -2.41878842]])

In [19]:
np.mean(temp,axis=1) #均值
np.std(temp,axis=1) #标准差-描述波动性
np.var(temp,axis=1) #方差-描述波动性

array([1.08768228, 0.64385364, 0.79324362, 0.71931149, 2.38035397])

In [12]:
# 条件赋值
temp[temp > 0.5] = 1
temp

array([[ 1.        , -1.88432601,  0.13684278,  1.        , -0.11515529],
       [-1.69726014,  1.        , -0.55892912, -0.91538695,  0.25244236],
       [-0.17848229,  1.        ,  1.        ,  0.31832621, -0.3068495 ],
       [ 1.        ,  1.        , -0.34740352,  1.        ,  1.        ],
       [ 1.        , -1.51983301,  1.        ,  1.        , -2.41878842]])

In [15]:
# 对于大于0 的值变为1 其他为0
temp = np.where(temp>0,1,0)
temp

array([[1, 0, 1, 1, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 1, 1, 0],
       [1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0]])

In [17]:
# 复合运算
temp = np.where(np.logical_or(temp>0,temp<1),1,0) #logical_or和logical_and
temp

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
list1 = range(10)  # 生成一个1行10列的矩阵
data2 = np.array(list1)
print(data2)
print('各维度大小',data2.shape)

[0 1 2 3 4 5 6 7 8 9]
各维度大小 (10,)


In [6]:
arr_1 = np.arange(5)
arr_2 = np.arange(5,dtype=float) #浮点型显示
arr_3 = np.arange(1,10,2) #左闭右开

"""
创建固定范围的数组
"""
arr_4 = np.linspace(0,100,10) # 左闭右闭

print(arr_1,arr_2,arr_3,arr_4)

[0 1 2 3 4] [0. 1. 2. 3. 4.] [1 3 5 7 9] [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [17]:
list2 = [range(10),range(10)] # 生成一个2行10列的矩阵
data3 = np.array(list2)
print(data3)
print('各维度大小',data3.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
各维度大小 (2, 10)


In [22]:
zeros_arr = np.zeros((3,4)) # 全0矩阵
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
ones_arr = np.ones((3,4)) # 全1矩阵
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
ones_arr = np.ones([3,4]) # 全1矩阵
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
empty_arr = np.empty((3,6))
print(empty_arr)

[[6.23042070e-307 1.86918699e-306 1.69121096e-306 1.33511562e-306
  1.42419938e-306 7.56603881e-307]
 [8.45603441e-307 1.42417221e-306 1.60219306e-306 6.23059726e-307
  1.06811422e-306 1.42417221e-306]
 [1.37961641e-306 6.23039354e-307 6.23053954e-307 8.01100605e-307
  8.34451504e-308 9.34531022e-307]]


In [31]:
empty_enpty_arr = np.empty((3,6),int)
print(empty_enpty_arr)

[[         0          0          0          0          0          0]
 [         0          0          0          0       1324          0]
 [         0          0          0          0 -202628624        456]]


In [33]:
a = np.array([2,23,4],dtype = np.int64) # 生成一个指定的1行3列矩阵
print(a)

[ 2 23  4]


In [32]:
b = np.array([[2,23],[2,32]]) # 生成一个指定的2行2列矩阵
print (b)

[[ 2 23]
 [ 2 32]]


In [41]:
e = np.arange(12).reshape((3,4)) # 生成一个3行4列的矩阵，12个数值 = array(range(12))
f = np.array(range(12)).reshape(3,4) #两种写法等价
print (e)
print (f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
f = e**2   # 矩阵中的每个值求平方
print (f)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [43]:
g = 10*np.sin(f)  # 正弦函数，乘法
print (g)

[[ 0.          8.41470985 -7.56802495  4.12118485]
 [-2.87903317 -1.3235175  -9.91778853 -9.53752653]
 [ 9.20026038 -6.29887994 -5.06365641  9.98815225]]


In [44]:
print (f<100) #判断，布尔类型

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]]


In [47]:
# 矩阵乘法
h = np.dot(b,b)
print (h)

[[  50  782]
 [  68 1070]]


In [49]:
# 返回一个0~1之间得随机数，形状为2行*4列的矩阵
i = np.random.random((2,4))
i

array([[0.35132693, 0.82157914, 0.39887   , 0.671085  ],
       [0.6521914 , 0.75335833, 0.78101865, 0.10407246]])

In [15]:
i = np.floor(10*np.random.random((3,4))) # floor 向下取整
print(i)
print(i.ravel()) # 将矩阵拉平，成为一个向量
i.shape = (2,6) # 指定将向量的形状
print(i)

[[3. 0. 3. 5.]
 [2. 3. 3. 5.]
 [6. 5. 1. 6.]]
[3. 0. 3. 5. 2. 3. 3. 5. 6. 5. 1. 6.]
[[3. 0. 3. 5. 2. 3.]
 [3. 5. 6. 5. 1. 6.]]


In [33]:
# 返回一个样本，具有标准正态分布。
i = np.random.randn()
i

0.1025217213337806

In [34]:
# 返回随机的整数，位于半开区间 [low, high)。
i = np.random.randint(9,15,size=(2,4))
print (i)

[[11  9 11 12]
 [10  9 11 10]]


In [36]:
# 两种求和方法效果一样
print(np.sum(i,axis = 1)) #对每一行求和
print(i.sum(axis = 1)) # axis = 1 为横向的意思
print(i.sum(axis = 0)) # axis = 0 为纵向的意思

[43 40]
[43 40]
[21 18 22 22]


In [62]:
# 列：axis = 0 行：axis = 1
print (np.max(i,axis = 0)) #对每一列找最大值
print (np.min(i,axis = 0)) #对每一列找最大值

[14 14 12 14]
[13 12 11 11]


In [17]:
A = np.arange(2,14).reshape((3,4)) #将2，14的一维数组转为3行4列的二维数组
print(A)
print (np.argmin(A)) #最小值索引

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0


In [67]:
print (np.argmax(A)) #最大值索引

11


In [68]:
print (np.mean(A)) #平均值

7.5


In [69]:
print (np.median(A)) #中位数

7.5


In [70]:
print (np.cumsum(A)) #逐步累加

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [71]:
print (np.diff(A)) #累差

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [72]:
print (np.nonzero(A)) #非0值的位置
'''
简单来说就是参数是数组或者矩阵，返回值为该数组或者矩阵中非零元素的下标值构成的元组。该元组有两维，第一维是非零元素所在的行，第二维是非零元素所在的列。
如果

a=mat([ [1,0,0],         
       [1,0,0],
        [0,0,0]])                      
则 nonzero(a) 返回值为 (array([0, 1]), array([0, 0])) , 因为矩阵a只有两个非零值， 在第0行、第0列，和第1行、第0列。所以结果元组中，第一个行维度数据为（0,1） 元组第二个列维度都为（0,0）。
'''

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [73]:
print (np.sort(A)) #矩阵排序

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [74]:
print (np.transpose(A)) #矩阵的转置

[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


In [75]:
print (A.T) #同上

[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


In [76]:
print ((A.T).dot(A)) #A的转置与A的矩阵乘法

[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]


In [77]:
print (np.clip(A,5,9)) #保留A中大于5小于9的数，小于5的值转为5，大于9的值转为9

[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [78]:
print (np.mean(A,axis=1)) #对每一行求平均值

[ 3.5  7.5 11.5]


In [31]:
# 重新设置维度：reshape和resize
arr_1 = np.arange(1,21) #生成1到20的一维数组
print(arr_1)
print(arr_1.reshape(4,5)) # 转成4*5的二维数组，这里行和列的乘积必须等于一维数组的元素个数
print(arr_1.reshape(2,10)) # 转成2*10的二维数组。
print("-"*50)
arr_1.resize(4,5)
print(arr_1)
arr_1.resize(2,10)
print(arr_1)

print("-"*50)


# 降维：多维降为一维ravel和flatten
arr_2 = np.arange(1,25) #生成1到20的一维数组
arr_2 = arr_2.reshape(4,6) # 一维转多维
#print(arr_2.ravel()) # 多维转一维
print(arr_2.flatten()) # 多维转一维

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
--------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
--------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [79]:
# 索引
B = np.arange(3,15).reshape(3,4)
print (B)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [80]:
print (B[1][1])
print (B[2,1])

8
12


In [81]:
print (B[:,1]) #第1列的所有数
print (B[1,2:4]) #第一行第2位到第3位的数

[ 4  8 12]
[ 9 10]


In [82]:
# 通过循环来打印每一行
for row in B:
    print (row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [83]:
# 通过循环来打印（转置）列
for column in B.T:
    print (column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [91]:
# 打印每一个项目
for item in B.flat:
    print (item)

3
4
5
6
7
8
9
10
11
12
13
14


In [92]:
# 将矩阵转为一行
print (B.flatten())

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [95]:
# 矩阵的合并
C = np.array([1,1,1])
D = np.array([2,2,2])
E = np.vstack((C,D)) #上下合并
print (E)
print (E.shape,C.shape) #打印E和C的形状

[[1 1 1]
 [2 2 2]]
(2, 3) (3,)


In [96]:
F = np.hstack((C,D)) #左右合并
print (F)
print (F.shape,C.shape)

[1 1 1 2 2 2]
(6,) (3,)


In [98]:
G = C[np.newaxis,:] #在行上增加一个维度
print (G)
print (G.shape)

[[1 1 1]]
(1, 3)


In [99]:
H = C [:,np.newaxis] #在列上增加一个维度
print (H)
print (H.shape)

[[1]
 [1]
 [1]]
(3, 1)


In [100]:
I = np.hstack((C[:,np.newaxis],D[:,np.newaxis])) #左右合并
print (I)
print (I.shape)

[[1 2]
 [1 2]
 [1 2]]
(3, 2)


In [101]:
# 多个array进行合并
J = np.concatenate((C[:,np.newaxis],D[:,np.newaxis],D[:,np.newaxis],C[:,np.newaxis]),axis=0) #纵向合并
print (J)
print (J.shape)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
(12, 1)


In [102]:
K = np.concatenate((C[:,np.newaxis],D[:,np.newaxis],D[:,np.newaxis],C[:,np.newaxis]),axis=1) #横向合并
print (K)
print (K.shape)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
(3, 4)


In [103]:
A = np.arange(12).reshape((3,4))
print (A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [104]:
print (np.split(A,2,axis=1)) #纵向均等分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [105]:
print (np.split(A,3,axis=0)) #横向均等分割

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [106]:
print (np.array_split(A,3,axis=1)) #纵向不等分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [107]:
# 关联赋值，a值改变，全部改变
a = np.arange(4)
print (a)
b=a
c=a
d=b
a[0] = 11
print (b)
print (d)

[0 1 2 3]
[11  1  2  3]
[11  1  2  3]


In [108]:
# 非关联赋值
e = a.copy()
a[3] = 33
print (a)
print (e)

[11  1  2 33]
[11  1  2  3]


In [7]:
vector = np.array([5,10,15,20])
equal_to_ten_and_five = (vector == 10) & (vector == 5)  # 判断某个值是否等于5和10
equal_to_ten_or_five = (vector == 10) | (vector == 5)  # 判断某个值是否等于5或10
print(equal_to_ten_and_five)
print(equal_to_ten_or_five)

[False False False False]
[ True  True False False]


In [8]:
vector = np.array(["1","2","3"])
vector = vector.astype(float)  # astype 函数转换类型
print(vector)

[1. 2. 3.]


In [22]:
aa = np.array([[1,2,3],[4,5,6]])
display(aa.size) # 在jupyter中可以用display打印



c,v = np.loadtxt('HomeWork1.csv',delimiter=',',usecols=(2,3),unpack=True,encoding='utf-8')
display(c)
display(v)

d = np.mean(c) # 普通平均值
display(d)

ave = np.average(c,weights=v) # 以v为权重计算平均
display(ave)

t = np.arange(len(c))
display(t)
ave = np.average(c,weights=t) # 以靠近的日期为高权重计算平均
display(ave)

median = np.median(c) # 中位数
display(median)

var = np.var(c) # 方差
display(var)

std = np.std(c) # 标准差
display(std)

diff = np.diff(c) # 关联性
display(diff) #后一个值减前一个值
display(c)

# 可以用来计算每日股票收益率
rate = diff/c[:-1] # 从第0个开始切片，到倒数第1个值切片
display(rate)

# 看看拿些天是大于0的
np.where(rate>0)

6

array([51., 33., 32., 31., 32., 26., 28., 25., 27., 28., 27., 29., 21.])

array([229., 205., 222., 213., 221., 193., 200., 167., 181., 195., 157.,
       163., 144.])

30.0

30.663855421686748

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

26.923076923076923

28.0

46.76923076923077

6.838803314120883

array([-18.,  -1.,  -1.,   1.,  -6.,   2.,  -3.,   2.,   1.,  -1.,   2.,
        -8.])

array([51., 33., 32., 31., 32., 26., 28., 25., 27., 28., 27., 29., 21.])

array([-0.35294118, -0.03030303, -0.03125   ,  0.03225806, -0.1875    ,
        0.07692308, -0.10714286,  0.08      ,  0.03703704, -0.03571429,
        0.07407407, -0.27586207])

(array([ 3,  5,  7,  8, 10], dtype=int64),)

In [36]:
data = np.genfromtxt('HomeWork1.csv',delimiter=',') # 读取文件
data

array([[  nan,  229.,   51.,  229.,   51.,  229.,   51.,    0.],
       [  84.,  434.,   33.,  205.,   40.,  204.,   91.,    8.],
       [ 116.,  656.,   32.,  222.,   41.,  221.,  133.,   17.],
       [ 147.,  869.,   31.,  213.,   41.,  212.,  173.,   26.],
       [ 179., 1090.,   32.,  221.,   42.,  218.,  215.,   36.],
       [ 205., 1283.,   26.,  193.,   37.,  195.,  253.,   47.],
       [ 233., 1484.,   28.,  200.,   39.,  201.,  291.,   58.],
       [ 259., 1650.,   25.,  167.,   35.,  167.,  326.,   68.],
       [ 285., 1831.,   27.,  181.,   37.,  185.,  364.,   78.],
       [ 313., 2026.,   28.,  195.,   38.,  190.,  402.,   89.],
       [ 340., 2183.,   27.,  157.,   36.,  165.,  438.,   98.],
       [ 369., 2345.,   29.,  163.,   38.,  165.,  476.,  107.],
       [ 390., 2490.,   21.,  144.,   30.,  141.,  506.,  116.]])

In [32]:
c,v = np.loadtxt('HomeWork1.csv',delimiter=',',usecols=(2,3),unpack=True,encoding='utf-8') # 读取文件中的某xx列
print(c,v)

[51. 33. 32. 31. 32. 26. 28. 25. 27. 28. 27. 29. 21.] [229. 205. 222. 213. 221. 193. 200. 167. 181. 195. 157. 163. 144.]
