In [6]:
import numpy as np
from numpy import genfromtxt
from sklearn import linear_model
import matplotlib.pyplot as plt

In [10]:
data = genfromtxt('data.csv',delimiter=',')
x_data = data[56:,2:-1]
y_data = data[56:,1]
print(x_data)
print(y_data)

[[2.8 4.5 1.3]
 [3.3 4.7 1.6]
 [2.4 3.3 1. ]
 [2.9 4.6 1.3]
 [2.7 3.9 1.4]
 [2.  3.5 1. ]
 [3.  4.2 1.5]
 [2.2 4.  1. ]
 [2.9 4.7 1.4]
 [2.9 3.6 1.3]
 [3.1 4.4 1.4]
 [3.  4.5 1.5]
 [2.7 4.1 1. ]
 [2.2 4.5 1.5]
 [2.5 3.9 1.1]
 [3.2 4.8 1.8]
 [2.8 4.  1.3]
 [2.5 4.9 1.5]
 [2.8 4.7 1.2]
 [2.9 4.3 1.3]
 [3.  4.4 1.4]
 [2.8 4.8 1.4]
 [3.  5.  1.7]
 [2.9 4.5 1.5]
 [2.6 3.5 1. ]
 [2.4 3.8 1.1]
 [2.4 3.7 1. ]
 [2.7 3.9 1.2]
 [2.7 5.1 1.6]
 [3.  4.5 1.5]
 [3.4 4.5 1.6]
 [3.1 4.7 1.5]
 [2.3 4.4 1.3]
 [3.  4.1 1.3]
 [2.5 4.  1.3]
 [2.6 4.4 1.2]
 [3.  4.6 1.4]
 [2.6 4.  1.2]
 [2.3 3.3 1. ]
 [2.7 4.2 1.3]
 [3.  4.2 1.2]
 [2.9 4.2 1.3]
 [2.9 4.3 1.3]
 [2.5 3.  1.1]
 [2.8 4.1 1.3]
 [3.3 6.  2.5]
 [2.7 5.1 1.9]
 [3.  5.9 2.1]
 [2.9 5.6 1.8]
 [3.  5.8 2.2]
 [3.  6.6 2.1]
 [2.5 4.5 1.7]
 [2.9 6.3 1.8]
 [2.5 5.8 1.8]
 [3.6 6.1 2.5]
 [3.2 5.1 2. ]
 [2.7 5.3 1.9]
 [3.  5.5 2.1]
 [2.5 5.  2. ]
 [2.8 5.1 2.4]
 [3.2 5.3 2.3]
 [3.  5.5 1.8]
 [3.8 6.7 2.2]
 [2.6 6.9 2.3]
 [2.2 5.  1.5]
 [3.2 5.7 2.3]
 [2.8 4.9 

In [11]:
# 建模
model = linear_model.ElasticNetCV()
model.fit(x_data,y_data)

# 弹性网系数
print(model.alpha_)
# 相关系数
print(model.coef_)

0.004055020490131288
[ 0.35770324  0.77482009 -0.4340634 ]


In [12]:
model.predict(x_data[-2,np.newaxis])

array([6.54372153])