### 实现train_test_split

In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
shuffle_indexs = np.random.permutation(len(X))

In [6]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

test_indexs = shuffle_indexs[:test_size]
train_indexs = shuffle_indexs[test_size:]

In [7]:
test_indexs.shape

(30,)

In [8]:
train_indexs.shape

(120,)

In [9]:
X_train = X[train_indexs]
y_train = y[train_indexs]

X_test = X[test_indexs]
y_test = y[test_indexs]

In [10]:
len(X_train)

120

In [11]:
len(y_train)

120

In [12]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train,y_train)

KNeighborsClassifier()

In [13]:
y_predict = knn_clf.predict(X_test)

In [14]:
y_predict

array([1, 2, 2, 0, 2, 0, 1, 0, 2, 2, 2, 1, 1, 0, 0, 0, 2, 1, 2, 1, 2, 0,
       0, 0, 1, 2, 0, 1, 2, 2])

In [15]:
y_test

array([1, 2, 2, 0, 2, 0, 1, 0, 2, 1, 2, 1, 1, 0, 0, 0, 2, 1, 2, 1, 2, 0,
       0, 0, 1, 2, 0, 1, 2, 2])

In [16]:
np.sum(np.array(y_predict == y_test,dtype='int'))/len(X_test)

0.9666666666666667

### 使用sklearn中封装好的train_test_split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y) # 调用sklearn中的train_test_split，返回四个结果

In [19]:
X_train.shape

(112, 4)

In [20]:
X_test.shape

(38, 4)

In [21]:
knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train,y_train)

KNeighborsClassifier()

In [22]:
knn_clf.predict(X_test) # 传入待预测的样本特征，得到预测结果

array([0, 0, 1, 2, 2, 1, 2, 0, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 0, 1, 1, 2,
       1, 1, 1, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 2, 1])

In [23]:
knn_clf.score(X_test,y_test) # 传入X_test和y_test，得到预测的准确率

0.9736842105263158

In [ ]:
KNeighborsClassifier(n_neighbors=6)